version: "3.10"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15

  django:
    build:
      context: .
      dockerfile: Dockerfile_django
    volumes:
      - .:/Car_owners
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    entrypoint: sh -c "chmod +x /Car_owners/migrate.sh && sh /Car_owners/migrate.sh"