version: "3.10"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15

  django:
    build:
      context: .
      dockerfile: Dockerfile_django
    env_file:
      - .env
    volumes:
      - .:/Car_owners
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    entrypoint: sh -c "chmod +x /Car_owners/migrate.sh && sh /Car_owners/migrate.sh"
